[workspace]

members = [
    "generate",

    "6502",
    "65c02",
    "6805",
    "6809",
    "80251",
    "80390",
    "8051",
    "8085",
    "aarch64",
    "aarch64_applesilicon",
    "aarch64be",
    "arm4_be",
    "arm4_le",
    "arm4t_be",
    "arm4t_le",
    "arm5_be",
    "arm5_le",
    "arm5t_be",
    "arm5t_le",
    "arm6_be",
    "arm6_le",
    "arm7_be",
    "arm7_le",
    "arm8_be",
    "arm8_le",
    "avr8",
    "avr8e",
    "cp1600",
    "cr16b",
    "cr16c",
    "dalvik_base",
    "dalvik_dex_android10",
    "dalvik_dex_android11",
    "dalvik_dex_android12",
    "dalvik_dex_kitkat",
    "dalvik_dex_lollipop",
    "dalvik_dex_marshmallow",
    "dalvik_dex_nougat",
    "dalvik_dex_oreo",
    "dalvik_dex_pie",
    "dalvik_odex_kitkat",
    "data_be_64",
    "data_le_64",
    "dspic30f",
    "dspic33c",
    "dspic33e",
    "dspic33f",
    "h6309",
    "hc05",
    "hc08",
    "hcs08",
    "hcs12",
    "jvm",
    "m8c",
    "mcs96",
    "mips32be",
    "mips32le",
    "mips32r6be",
    "mips32r6le",
    "mips64be",
    "mips64le",
    "mx51",
    "pa_risc32be",
    "pic12c5xx",
    "pic16",
    "pic16c5x",
    "pic16f",
    "pic17c7xx",
    "pic18",
    "pic24e",
    "pic24f",
    "pic24h",
    "ppc_32_4xx_be",
    "ppc_32_4xx_le",
    "ppc_32_be",
    "ppc_32_le",
    "ppc_32_quicciii_be",
    "ppc_32_quicciii_le",
    "ppc_64_be",
    "ppc_64_isa_altivec_be",
    "ppc_64_isa_altivec_le",
    "ppc_64_isa_altivec_vle_be",
    "ppc_64_isa_be",
    "ppc_64_isa_le",
    "ppc_64_isa_vle_be",
    "ppc_64_le",
    "riscv.ilp32d",
    "riscv.lp64d",
    "sh_1",
    "sh_2",
    "sh_2a",
    "sparcv9_32",
    "sparcv9_64",
    "superh4_be",
    "superh4_le",
    "toy64_be",
    "toy64_be_harvard",
    "toy64_le",
    "toy_be",
    "toy_be_posstack",
    "toy_builder_be",
    "toy_builder_be_align2",
    "toy_builder_le",
    "toy_builder_le_align2",
    "toy_le",
    "toy_wsz_be",
    "toy_wsz_le",
    "tricore",
    "v850",
    "x86",
    "x86_64",
    "z180",
    "z80",
]
